apiVersion: v1
kind: Service
metadata:
  name: coll-fa26a81b52a144a2979ec8b532474c7b-srv
spec:
  selector:
    app: coll-fa26a81b52a144a2979ec8b532474c7b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP